# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'not_giris_ekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(886, 597)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_not_defteri = QtWidgets.QLabel(self.centralwidget)
        self.label_not_defteri.setGeometry(QtCore.QRect(300, 70, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.label_not_defteri.setFont(font)
        self.label_not_defteri.setObjectName("label_not_defteri")
        self.pushButton_not_ekle = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_not_ekle.setGeometry(QtCore.QRect(350, 230, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_not_ekle.setFont(font)
        self.pushButton_not_ekle.setObjectName("pushButton_not_ekle")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 300, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(390, 360, 91, 31))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_notAc = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_notAc.setGeometry(QtCore.QRect(390, 410, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_notAc.setFont(font)
        self.pushButton_notAc.setObjectName("pushButton_notAc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Not Defteri"))
        self.label_not_defteri.setText(_translate("MainWindow", "NOT DEFTERİ"))
        self.pushButton_not_ekle.setText(_translate("MainWindow", "Not Ekle"))
        self.label.setText(_translate("MainWindow", "Önceki Notlar"))
        self.pushButton_notAc.setText(_translate("MainWindow", "Notu Aç"))
